[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "firm-lens"
version = "1.0.1"
description = "Industrial-Grade Embedded IoT Firmware Security Analysis Engine"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Srikanth Rudrarapu" }
]

dependencies = [
    "rich",
    "click",
    "pycryptodome",
    "esptool>=4.5.0",
    "requests",
    "pyserial"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Topic :: Security",
    "Topic :: Software Development :: Embedded Systems",
]

[project.scripts]
firm-lens = "firm_lens.main:cli"

[tool.setuptools]
packages = ["firm_lens"]

# This ensures vulnerabilities.db and static rules are shipped to the user
[tool.setuptools.package-data]
firm_lens = ["data/*"]